### ISSUE TITLE
Error when %autochangelog is used

### ISSUE THREAD

**Issue by xsuchy** [packit/specfile#123]
When parsing https://src.fedoraproject.org/rpms/gssntlmssp/blob/rawhide/f/gssntlmssp.spec
specfiles throws
```
Traceback (most recent call last):
  File "/home/msuchy/projects/license-validate/./print-spec-changelog.py", line 10, in <module>
    print(sections.changelog)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/sections.py", line 144, in __getattr__
    raise AttributeError(name)
AttributeError: changelog
```

This is very likely due usage of `%autochangelog`

**Comment by nforro** [comment]
This is expected, as you are trying to access the `%changelog` section which doesn't exist. You can check for that first with `if 'changelog' in sections:`. There is also `Specfile.has_autochangelog` property, but it will return `False` in this case, because this particular spec file is malformed, AFAIK `%autochangelog` is supposed to be a macro within the `%changelog` section, not a section name by itself.

**Comment by xsuchy** [comment]
Fixed by changing the spec file https://src.fedoraproject.org/rpms/gssntlmssp/pull-request/1
