### ISSUE TITLE
UnboundLocalError: cannot access local variable 'spec' where it is not associated with a value

### ISSUE THREAD

**Issue by xsuchy** [packit/specfile#172]
Trying to parse `grub2.spec` from Fedora results in

```
Traceback (most recent call last):
  File "/home/msuchy/projects/license-validate/./print-spec-changelog.py", line 7, in <module>
    specfile = Specfile(filename, force_parse=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/specfile.py", line 57, in __init__
    self._parser.parse(str(self))
  File "/usr/lib/python3.11/site-packages/specfile/spec_parser.py", line 303, in parse
    self.spec, self.tainted = self._do_parse(content, extra_macros)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/spec_parser.py", line 281, in _do_parse
    del spec
        ^^^^
UnboundLocalError: cannot access local variable 'spec' where it is not associated with a value
```

**Comment by nforro** [comment]
Ok, this happens on a second attempt because there already are leftover dummy sources created by the previous attempt, which shouldn't happen and is now fixed in https://github.com/packit/specfile/pull/173.
However, that won't make this spec file parseable, as the `grub.macros` file defines macros that are necessary for parsing. You can of course define them manually:

```python
spec = Specfile('grub2.spec', force_parse=True, macros=[("with_legacy_arch", "0"), ("with_efi_arch", "0"), ("with_alt_efi_arch", "0"), ("with_emu_arch", "0")])
```

But that's not something that could be automated.

**Comment by nforro** [comment]
I've marked #173 as fixing this issue, because it does fix the reported `UnboundLocalError`. Parsing `grub2.spec` will still fail, without explicitly defining the necessary macros, but that's not really a specfile issue.
