### ISSUE TITLE
Cannot parse %shrink

### ISSUE THREAD

**Issue by xsuchy** [packit/specfile#410]
### What happened? What is the problem?

Package python-graph-tool has this lines in a spec file:
```
License:        %{shrink:
                LGPL-3.0-or-later AND
                BSL-1.0 AND
                BSD-3-Clause AND
                GPL-3.0-or-later AND
                MIT AND
                (MIT OR Apache-2.0)
                }
```
Then I try to print the license tag using https://pagure.io/copr/license-validate/blob/main/f/print-spec-license.py

I get:
```
$ ./print-spec-license.py rpm-specs/python-graph-tool.spec
%{shrink:
LGPL-3.0-or-later AND BSL-1.0
```

### Steps to reproduce

```bash
1.
2.
3.
```

### Workaround

- [ ] There is an existing workaround that can be used until this issue is fixed.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by gotmax23** [comment]
The code to parse tags apparently uses a regex that assumes macros are one line and doesn't account for multi-line macros. Your script should probably use the `expanded_value` property instead of `value`. License tags can have macros and other expansions that should be evaluated. In this case, it would loudly fail because of the parser issue, but otherwise, it would do the right thing.

**Comment by gotmax23** [comment]
For what it's worth:

``` console
$ rg 'License:.*%\{shrink' -l | wc -l
19
```
